### ISSUE TITLE
First map needs year note

### ISSUE THREAD

**Issue by tori-d** [technologiestiftung/grundsicherung#3]
The first map, showing the current situation in Berlin, needs a note somewhere saying that the data is from 31.12.2018.

This could go underneath the buttons? Or somewhere else?

**Comment by tori-d** [comment]
Based on call, suggestion is bottom left, but in reality can go anywhere it's easy to place.

Suggested text:

_Bezugsdatum: 31.12.2018_

**Comment by Lisa-Stubert** [comment]
text added on bottom left
